### ISSUE TITLE
Rename 'knobs' prop to something else

### ISSUE THREAD

**Issue by amalik2** [storybookjs/native#36]
Currently we have an optional prop called knobs that is included in renderer components for convenience. Since knobs are deprecated by Storybook now, this should be renamed something else. This will be a breaking change so it would probably be a good idea to make this change after Storybook v7 is released

**Comment by sumwatshade** [comment]
:rocket: Issue was released in [`v2.0.0`](https://github.com/storybookjs/native/releases/tag/v2.0.0) :rocket:
