### ISSUE TITLE
Allow interaction with emulators open on local machine

### ISSUE THREAD

**Issue by amalik2** [storybookjs/native#47]
Run storybook in an electron app that communicates with open emulator on local machine instead of with appetize.io so that local changes are easier to test

**Comment by amalik2** [comment]
After looking into this, we don't need an electron app for this. Extending the storybook express server allows us to accomplish the same result

**Comment by sumwatshade** [comment]
:rocket: Issue was released in [`v2.0.0`](https://github.com/storybookjs/native/releases/tag/v2.0.0) :rocket:
