### ISSUE TITLE
"App not found, please verify URL" when attempting to install native iOS example

### ISSUE THREAD

**Issue by arixegal** [storybookjs/native#75]
### Describe the bug

When attempting to install the native iOS examples on a local Node JS server, the following error is received in the dashboard:
App not found, please verify URL

I believe it might be because a wrong appetize.io api key is used, but I can't find any example of how to use this key and where it should be embedded. The relevant section in the documentation says:

you must upload your application to [appetize.io](https://appetize.io/). After the upload, you will receive a public key that can be used with Storybook Native to view and interact with your application directly from Storybook.

So now that I have uploaded the demo app to appetize.io and received a public key, I can't understand what to do with it and how I can tell the system that this is the key that should be used.

Is there any documentation about it?

### Expected behavior

I expected to see a storybook with an integrated appetize build.

### Environment

 - OS: macOS Monterey
 - Node.js version: v18.7.0.
 - NPM version: npm@8.15.0
 - Browser Chrome
 - Browser version (if applicable): Version 104.0.5112.79 (Official Build) (arm64)

**Comment by arixegal** [comment]
Found it. Sorry. I'm closing the issue

**Comment by marcosmko** [comment]
Hey @arixegal, can you share the documentation please?
I have the same problems that you had.

**Comment by arixegal** [comment]
@marcosmko 
It's been a while and our iOS story-book was discontinued. One of the reasons was that we had decided that iOS support for this product is premature. Since you asked, I took a look and found a key in a file called _button.stories.jsx,_ this is how it looks: 

/*
import React from "react";
import { Description } from "@storybook/addon-docs/blocks";
import { EmulatorRenderer } from "@storybook/native-components";

export default {
    title: "Button"
};

export const Example = (props) => {
    return (
        <EmulatorRenderer
            apiKey="---------------------" // <--- Over here
            platform="ios"
            storyParams={{ component: "button" }}
            deepLinkBaseUrl="sb-native://deep.link"
            knobs={props}
        />
    );
};

Example.parameters = {
    docs: {
        page: () => <Description markdown={undefined} />
    }
};
*/

**Comment by marcosmko** [comment]
Thanks!
