### ISSUE TITLE
An example using React Native and Expo would be helpful

### ISSUE THREAD

**Issue by jeromecovington** [storybookjs/native#88]
It would be very helpful in addition to the native demos with deep linking in Swift, etc. to have an example using React Native via Expo since it is such a common framework. I can help put one together, but I am still puzzling through the docs for this repo, how best to setup the deep linking configuration, and so on. If such an example already exists (either made by the maintainers of this project or if one is known from a blog post or other resource) it would be great to know about it.

**Comment by ahna92** [comment]
hi @jeromecovington 
have you checked [react-native storybook](https://storybook.js.org/tutorials/intro-to-storybook/react-native/en/get-started/)

**Comment by jeromecovington** [comment]
@ahna92 yes I was able to get Storybook running in the simulator in Expo using a process similar to the one you mentioned. I'm sorry I didn't close the issue, but I will do so now. Thanks!
